1. **Vektor** 
*Deklarasi* variabel diawali dengan
Vektor dapat dituliskan dengan dan tanpa bantuan *library*

In [ ]:
# vektor python numpy with range value
import numpy as np
print("vektor default python\n")
a = np.arange(1,20,1)
b = np.arange(1,20,2)

import numpy as np
print (" \n vektor via numpy \n")
# vektor via numpy 
c = np.array ([1,2,3,4,5])
d = np.array ([1.5, 2.5, 5, 6, 7])

print(a)
print(b)
print(a.ndim)
print(a.shape)


vektor default python

 
 vektor via numpy 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
1
(19,)


2.	**Matrix**
*Matriks* adalah *basic 2D table* dari data dan dapat berisi nilai numerik dan/atau karakter. Dapat dibuat dengan cara sederhana dengan membuat urutan dari vektor, mengubah dari vektor atau membaca dari file

In [ ]:
# mengubah dari 1D menjadi matrik 2D 
a = np.arange(1,21,1)
c = a.reshape((4,5))
print(c)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


3.	***List***
*List* merupakan merupakan representasi struktur data yang dapat menyimpan data dengan nilai numerik, karakter, dan lain-lain secara bersamaan


In [ ]:
list1 = ["apple", "banana", "cherry"]
list2 = [1, 5, 7, 9, 3]
list3 = [True, False, False]
list4 = ["abc", 34, True, 40, "male"]

print(list1);


['apple', 'banana', 'cherry']


4.	***data.Frame***
*Data frame* adalah spesialisasi dari tipe list untuk menyimpan vektor ke dalam bentuk frame (menyerupai basis data). Kelebihan dibandingkan matriks adalah dapat dimanipulasi dalam berbagai bentuk dan cara

In [ ]:
#data frame
import pandas as pd
df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
                        columns=['a', 'b', 'c'])

print(df)

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9


5.	***Import Data (loading data in Python: csv, text, XML, image)***
*Buat* file dengan header, misalkan terdiri dari Nama Pasien, Umur, Penyakit, Gender seperti pada tabel berikut dan simpan kedalam format CSV dan Text (Tab delimeter)


In [ ]:
# Membaca data dari file dengan format CSV
import pandas as pd
from google.colab import files
filenya =files.upload()

Saving Data.csv to Data.csv


In [ ]:
# Membaca data dari file dengan format CSV
import pandas as pd
data = pd.read_csv("Data.csv", sep=";")
print(data)

   Nama Pasien  Umur Gender Diagnosa Sakit
0         Anto    24      L          Tidak
1         Budi    35      L             Ya
2          Adi    55      L             Ya
3       Delima    32      P             Ya
4         Dodi    21      L          Tidak
5      Tukiyem    19      P          Tidak
6         Rama    23      L          Tidak
7        Santi    35      P          Tidak
8         Mery    44      P             Ya
9        Yanti    27      P          Tidak
10       Parto    43      L             Ya
11         Dea    24      P          Tidak
